#cloud-config
rancher:
  cloud_init:
    datasources:
      - waagent
  services:
    waagent:
      image: waagent
      command: -daemon
      privileged: true
      restart: always
      environment:
        DISTRO_NAME: RancherOS
      labels:
        io.rancher.os.scope: system
        io.rancher.os.after: cloud-init-pre
      volumes_from:
      - all-volumes
      volumes:
      - /var/lib/waagent:/var/lib/waagent
      net: host
      uts: host
      ipc: host
      pid: host
